# -----------------------------------------------------------------------------
# MDX Gen - A robust Rust library for processing Markdown and converting it to HTML
# with support for custom blocks, enhanced table formatting, and flexible configuration options.
# -----------------------------------------------------------------------------

[package]
name = "mdx-gen"
version = "0.0.1"
edition = "2021"
rust-version = "1.56.0"
license = "MIT OR Apache-2.0"
description = """
A robust Rust library for processing Markdown and converting it to HTML with support for custom blocks, enhanced table formatting, and flexible configuration options.
"""
homepage = "https://mdxgen.com/"
documentation = "https://mdxgen.com/documentation/index.html"
repository = "https://github.com/sebastienrousseau/mdx-gen"
readme = "README.md"
build = "build.rs"

# -----------------------------------------------------------------------------
# Crate Configuration
# -----------------------------------------------------------------------------

categories = [
    "command-line-utilities",
    "data-structures",
    "text-processing",
    "parsing",
    "development-tools"
]

keywords = ["markdown", "html", "generator", "mdx-gen", "static"]

# Exclude unnecessary files from the crate
exclude = [
    "/.git/*", "/.github/*", "/.gitignore", "/.vscode/*"
]

# -----------------------------------------------------------------------------
# Dependencies
# -----------------------------------------------------------------------------

[dependencies]
anyhow = "1.0"
comrak = "0.29"
env_logger = "0.11"
html-escape = "0.2"
lazy_static = "1.5"
log = "0.4"
regex = "1.11"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0"
serde_yml = { version = "0.0.12", optional = true }
syntect = { version = "5.2", optional = true }
thiserror = "2.0"
tokio = { version = "1.40", features = ["full"] }
toml = "^0.8"

[build-dependencies]
version_check = "0.9"

[lib]
name = "mdx_gen"
path = "src/lib.rs"

# -----------------------------------------------------------------------------
# Features
# -----------------------------------------------------------------------------

[features]
# Default feature set includes syntax highlighting, custom blocks, and enhanced tables.
default = ["syntax_highlighting", "custom_blocks", "enhanced_tables"]

# Enable syntax highlighting using syntect
syntax_highlighting = ["syntect"]

# Enable custom block processing
custom_blocks = []

# Enable enhanced table formatting
enhanced_tables = []

# Enable YAML support
yaml_support = ["serde_yml"]

# -----------------------------------------------------------------------------
# Development Dependencies
# -----------------------------------------------------------------------------

[dev-dependencies]
tempfile = "3.13"
assert_fs = "1.1"
predicates = "3.1"
criterion = "0.5"

[[bench]]
name = "markdown_benchmark"
harness = false

[profile.bench]
debug = true
