# Cargo.toml - Configuration file for the MDX Gen library.
# Copyright © 2024 MDX Gen. All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
# Metadata about the package.
name = "mdx-gen"                            # The name of the library
version = "0.0.1"                           # Initial version of the crate
authors = ["MDX Generator Contributors"]    # Library contributors
edition = "2021"                            # Rust edition being used
rust-version = "1.56.0"                     # Minimum supported Rust version
license = "MIT OR Apache-2.0"               # Dual licensing strategy
description = """
A robust Rust library for processing Markdown and converting it to HTML with support for custom blocks, enhanced table formatting, and flexible configuration options.
"""                                         # Short library description
homepage = "https://mdxgen.com/"             # Project's homepage URL
documentation = "https://mdxgen.com/documentation/index.html" # Doc URL
repository = "https://github.com/sebastienrousseau/mdx-gen"    # Repository URL
readme = "README.md"                        # Path to the readme file
build = "build.rs"                          # Path to the build script

categories = [
    "text-processing",
    "html",
    "static-site-generators",
    "parsing",
    "development-tools",
]


[dependencies]
# Dependencies required for building and running the project.
anyhow = "1.0"
comrak = "0.28"
env_logger = "0.11"
html-escape = "0.2"
lazy_static = "1.5"
log = "0.4"
regex = "1.11"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0"
serde_yml = "0.0.12"
syntect = "5.2"
thiserror = "1.0"
toml = "0.8"

[build-dependencies]
# Dependencies for build scripts.
version_check = "0.9" # Check the Rust version used to compile the package.

[lib]
name = "mdx_gen"
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3.13"
assert_fs = "1.1"
predicates = "3.1"
criterion = "0.5"

[[bench]]
name = "markdown_benchmark"
harness = false
